#############################################################################
# Makefile for building: palmyrafm
# Generated by qmake (1.07a) (Qt 3.3.4) on: Sun Apr 30 13:34:28 2006
# Project:  palmyrafm.pro
# Template: app
# Command: $(QMAKE) -o Makefile palmyrafm.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -m32 -march=i386 -mtune=pentium4 -fasynchronous-unwind-tables  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt-3.3/mkspecs/default -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = palmyrafm.h \
		dirview.h
SOURCES = main.cpp \
		palmyrafm.cpp \
		dirview.cpp
OBJECTS = main.o \
		palmyrafm.o \
		dirview.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_palmyrafm.cpp \
		moc_dirview.cpp
OBJMOC = moc_palmyrafm.o \
		moc_dirview.o
DIST	   = palmyrafm.pro
QMAKE_TARGET = palmyrafm
DESTDIR  = 
TARGET   = palmyrafm

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: palmyrafm.pro  /usr/lib/qt-3.3/mkspecs/default/qmake.conf /usr/lib/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile palmyrafm.pro
qmake: 
	@$(QMAKE) -o Makefile palmyrafm.pro

dist: 
	@mkdir -p .tmp/palmyrafm && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/palmyrafm/ && ( cd `dirname .tmp/palmyrafm` && $(TAR) palmyrafm.tar palmyrafm && $(GZIP) palmyrafm.tar ) && $(MOVE) `dirname .tmp/palmyrafm`/palmyrafm.tar.gz . && $(DEL_FILE) -r .tmp/palmyrafm

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp palmyrafm.h

palmyrafm.o: palmyrafm.cpp palmyrafm.h \
		dirview.h

dirview.o: dirview.cpp dirview.h

moc_palmyrafm.o: moc_palmyrafm.cpp  palmyrafm.h 

moc_dirview.o: moc_dirview.cpp  dirview.h 

moc_palmyrafm.cpp: $(MOC) palmyrafm.h
	$(MOC) palmyrafm.h -o moc_palmyrafm.cpp

moc_dirview.cpp: $(MOC) dirview.h
	$(MOC) dirview.h -o moc_dirview.cpp

####### Install

install:  

uninstall:  

